@host = http://localhost:8080

### GET health
GET {{host}}/health

### GET health/check 
GET {{host}}/health/check?name=test&count=1

### GET test/param?msg=hello
GET {{host}}/test/param?msg=hello

### POST /test/body
POST http://localhost:8080/test/body
Content-Type: application/json

{
  "a": 1,
  "b": "text"
}

### POST test/body-dto
POST http://localhost:8080/test/body-dto
Content-Type: application/json

{
  "a": "hello",
  "b": 3
}

### GET param
GET http://localhost:8080/test/param?msg=hello

### GET page
GET http://localhost:8080/test/page

### GET page/값
GET http://localhost:8080/test/page?page=2&size=20

### GET hello
GET {{host}}/hello

### GET hello/json
GET {{host}}/hello/json